# Generated by Django 3.0 on 2019-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slig', models.SlugField(unique=True)),
                ('google_doc_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='id гугл документа')),
                ('category', models.CharField(choices=[('rockets', 'ракеты'), ('science', 'наука')], db_index=True, max_length=20, verbose_name='категория')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('teaser_text', models.TextField(blank=True, verbose_name='тизер')),
                ('teaser_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка тизера')),
                ('html', models.TextField(blank=True, help_text='HTML', verbose_name='текст')),
                ('source_title', models.CharField(blank=True, max_length=100, verbose_name='первоисточник')),
                ('source_link', models.URLField(blank=True, verbose_name='ссылка на первоисточник')),
                ('published', models.DateField(blank=True, help_text='оставьте пустым, чтобы скрыть из выдачи. Можно поставить будущее время', null=True, verbose_name='опубликовано')),
            ],
        ),
    ]
