# Generated by Django 3.0 on 2019-12-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slig',
            new_name='slug',
        ),
    ]
